config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "pages#home"
  get '/about', to: 'pages#about'
  get '/help', to: 'pages#help'

  resources :todos
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/todo.rb
class Todo < ApplicationRecord

  validates :name, presence: true
  validates :description, presence: true
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

    def home
        
    end

    def about

    end
    
    def help

    end


end

app/controllers/todos_controller.rb
class TodosController < ApplicationController

  before_action :set_todo_by_id, only: [:show, :edit, :update, :destroy]

  def new
    @todo = Todo.new
    
  end

  def create
    @todo = Todo.new(todo_params)

    if @todo.save
      flash[:notice] = "Todo is created succesfully !"
      redirect_to todo_path(@todo)
    else
      render 'new'
    end

  end

  def show
    
  end

  def edit
   
  end

  def update

    if @todo.update(todo_params)
      flash[:notice] = "Todo is updated"
      redirect_to todo_path(@todo)
    else
      render 'edit'
    end
    
  end


  def index
    @todo = Todo.all
    
  end

  def destroy
   
    @todo.destroy
    flash[:notice] = "Todo id deleted"
    redirect_to todos_path

  end


 

  private

   def todo_params
     params.require(:todo).permit(:name, :description)
   end

   def set_todo_by_id
    @todo = Todo.find(params[:id])
   end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg|%>
    <ul>
      <li> <%= msg %> </li>
    </ul>
    <%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Todoapp" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <%= render 'layouts/messages'%>
    <%= yield %>
    
  </body>
</html>

app/views/pages/about.html.erb
<h1> This is About page </h1>

    
<%= link_to "Go to add a new todo page", new_todo_path%>

app/views/pages/help.html.erb
<h1> This is help page <h1>

app/views/pages/home.html.erb
<h1> hello world </h1>

<h2> this is the test </h2>

app/views/todos/_form.html.erb
<% if @todo.errors.any?%>
<h2> The following errors are able to not save the data in database </h2>
    <ul>
        <% @todo.errors.full_messages.each do |msg|%>
        <li><%= msg %></li>
        <% end %>
    </ul>
<% end %>

<%= form_for @todo do |f|%>
<p>
    <%= f.label :name %>
    <br>
    <%= f.text_field :name%>
</p>

<p>
    <%= f.label :description %>
    <br>
    <%= f.text_area :description%>
</p>
<p>
    <%=f.submit %>
</p>
<% end %>


<%= link_to "Go to List page", todos_path%>
<%= link_to "Go to about page", about_path%>

app/views/todos/edit.html.erb
<h1>This is edit page</h1>

<%= render 'form'%>

app/views/todos/index.html.erb
<h1>This is Index page</h1>

<p>
    <%=link_to "Create Todo",new_todo_path%> 
</p>

<table>
    <tr>
        <th>Name</th>
        <th>Description</th>
    </tr>
    <% @todo.each do |todo|%>
    <tr>
        <td><%= todo.name%></td>
        <td><%= todo.description%></td>
        <td><%= link_to "Edit todo", edit_todo_path(todo)%></td>
        <td><%= link_to "Show todo", todo_path(todo)%></td>
        <td><%= link_to "Delete", todo_path(todo), method: :delete, data: {confirm: "Are you sure?"}%></td>
    </tr>
    <%end%>
</table>

app/views/todos/new.html.erb
<h1>Create a new todo</h1>

<%= render 'form'%>

app/views/todos/show.html.erb
<h1>This is Show page</h1>

<p>
    name: <%= @todo.name %>
</p>
<p>
    discription: <%= @todo.description%>
</p>


<%= link_to "Go to List page", todos_path%>
<br>
<%= link_to "Go to edit page", edit_todo_path(@todo) %>